### PR TITLE
Add newcomers workflow to notify about good first issues on slack

### LINKED ISSUE #219: [CI] Update Slack.yml and add newcomer-alert workflow
**Current Behavior**
Currently the slack.yml is outdated. Also there is no automated way of notifying the slack channel when a "good first issue" has been created.

**Desired Behavior**
Update slack.yml and add newcomer-alert.yml to the Github workflow. 

---
**Resources**
Add the updated slack.yml file and the newcomer-alert.yml file to the .github/workflow folder.

Files needed:
https://github.com/meshery/meshery-istio/blob/master/.github/workflows/slack.yml
https://github.com/layer5io/layer5/blob/master/.github/workflows/newcomers-alert.yml

### PR DESCRIPTION
**Pull request by Ankita13-code**
Signed-off-by: Ankita Pareek <ankitapareek2000@gmail.com>

**Description**
- This PR adds a workflow to notify about good first issues on the #newcomer channel of Layer5.
- The slack.yml file is already updated.

This PR fixes #219 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by theBeginner86 — APPROVED** [review]
LGTM 👍

Thank You @Ankita13-code 🚀

**Comment by theBeginner86** [comment]
@Ankita13-code could you please edit the PR description a bit. The slack.yml file is not updated. We are trying to propagate this workflow: https://github.com/meshery/meshery-istio/blob/master/.github/workflows/slack.yml

Also, after merging this PR, it would close the issue but we would not want that as there is a second part to the issue, i.e. `updating the slack workflow`. 

So, if you could please change the line `This PR fixes` to `This PR is related to` then that would be great 😁

**Comment by leecalcote** [comment]
@Ankita13-code @theBeginner86 what's the status of this effort? Duplicated and completed?

**Comment by theBeginner86** [comment]
@leecalcote we can merge this one. As newcomers-alert.yml is yet to be added to this repo.

**Comment by warunicorn19** [comment]
Thank you @Ankita13-code @theBeginner86

**Pull request merged**
