### PR TITLE
[CI] fix creation of commits in error codes utility workflow

### PR DESCRIPTION
**Pull request by iamsdas**
Signed-off-by: Suryashankar Das <suryashankardas.2002@gmail.com>

**Description**

This PR fixes the creation of commits in the meshery repo using the error codes utility workflow
Related to [this](https://github.com/meshery/meshery-istio/issues/267) issue

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by DelusionalOptimist — APPROVED** [review]

**Comment by DelusionalOptimist** [comment]
@iamsdas heads up. [This](https://github.com/meshery/meshery-kuma/commit/8e77eeb3dc079685c16704a3f163d34c03ef8de4) didn't update https://github.com/meshery/meshery-kuma/blob/8e77eeb3dc079685c16704a3f163d34c03ef8de4/internal/config/error.go#L24
Did you try using `**error.go` which should ideally update all directories?

**Comment by iamsdas** [comment]
> @iamsdas heads up. [This](https://github.com/meshery/meshery-kuma/commit/8e77eeb3dc079685c16704a3f163d34c03ef8de4) didn't update
> 
> https://github.com/meshery/meshery-kuma/blob/8e77eeb3dc079685c16704a3f163d34c03ef8de4/internal/config/error.go#L24
> 
> 
> Did you try using `**error.go` which should ideally update all directories?

Let me try it out in a github action...it didn't work in my terminal though (maybe due to zsh?)

**Comment by DelusionalOptimist** [comment]
Yes, prolly due to zsh. A general advice is to always test stuff related to CI in bash.

**Comment by iamsdas** [comment]
btw is there any reason why we are using `helpers/ **error.go` instead of simply using `.` ?

**Comment by DelusionalOptimist** [comment]
Yes. We don't want it to add anything other than those files accidentally.
[These](https://github.com/meshery/meshery-kuma/blob/be39c858d11c19fe447a28c39abc0f082a11f6f4/.github/workflows/error-ref-publisher.yml#L28-L29) commands might update go.mod and go.sum. we don't want this workflow to update dependencies.

**Comment by iamsdas** [comment]
Yup, its working with `**error.go`, I'll make another PR for it (and have updated the open PRs with it)

**Pull request merged**
